apiVersion: v1
kind: List
metadata:
 namespace: zabbix
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
     name: db-secret
     namespace: zabbix
    data:
     db-root-pass: "c29tZV90ZXN0X3Bhc3M="
     db-zbx-user: "zabbix78"
     db-zbx-pass: "emJ4X3Bhc3N3b3Jk"